#!/bin/bash

set -e

# shellcheck disable=SC1091
[ -f .env ] && . .env

[ ! -d node_modules ] && npm ci

PID=$(lsof -i :8545 -s TCP:LISTEN -t) || true
if [ -n "$PID" ]; then
  echo "Killing $PID"
  kill -TERM "$PID"
fi

npx hardhat node --fork "$NODE_URL" &