name: Avalanche Benqi XY Strategy
on:
  pull_request:
    paths:
      - ".github/workflows/avalanche-benqi-xy.yml"
      - ".github/actions/setup-env/action.yml"
      - "contracts/pool/**/*.sol"
      - "contracts/pool/*.sol"
      - "contracts/strategies/Strategy.sol"
      - "contracts/strategies/compound/CompoundXYCore.sol"
      - "contracts/strategies/compound/CompoundXYStrategy.sol"
      - "contracts/strategies/compound/BenqiXYStrategy.sol"
      - "contracts/strategies/compound/VesperBenqiXYStrategy.sol"
      - "test/avalanche/benqi-xy/**"

# Limit concurrency to one workflow per branch and one per pull_request
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  setup-job:
    runs-on: ubuntu-latest
    env:
      NODE_URL: ${{ secrets.AVALANCHE_NODE_URL }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup env
        uses: ./.github/actions/setup-env

  vawbtce-vesper-test:
    needs: [setup-job]
    runs-on: ubuntu-latest
    env:
      NODE_URL: ${{ secrets.AVALANCHE_NODE_URL }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup env
        uses: ./.github/actions/setup-env

      - name: Running Benqi Vesper XY strategy for VAWBTCe pool
        run: npm test test/avalanche/benqi-xy/vesper/vawbtce.js
