name: Avalanche Aave Strategy
on:
  pull_request:
    paths:
      - ".github/workflows/avalanche-aave.yml"
      - ".github/actions/setup-env/action.yml"
      - "contracts/pool/**/*.sol"
      - "contracts/pool/*.sol"
      - "contracts/strategies/Strategy.sol"
      - "contracts/strategies/aave/avalanche/AaveStrategy.sol"
      - "contracts/strategies/aave/avalanche/AaveCore.sol"
      - "test/avalanche/aave/**"

# Limit concurrency to one workflow per branch and one per pull_request
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  setup-job:
    runs-on: ubuntu-latest
    env:
      NODE_URL: ${{ secrets.AVALANCHE_NODE_URL }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup env
        uses: ./.github/actions/setup-env

  vaavax-test:
    needs: [setup-job]
    runs-on: ubuntu-latest
    env:
      NODE_URL: ${{ secrets.AVALANCHE_NODE_URL }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup env
        uses: ./.github/actions/setup-env

      - name: Running Aave strategy for VAAVAX pool
        run: npm test test/avalanche/aave/vaavax.js

  vadaie-test:
    needs: [setup-job]
    runs-on: ubuntu-latest
    env:
      NODE_URL: ${{ secrets.AVALANCHE_NODE_URL }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup env
        uses: ./.github/actions/setup-env

      - name: Running Aave strategy for VADAIe pool
        run: npm test test/avalanche/aave/vadaie.js

  vausdce-test:
    needs: [setup-job]
    runs-on: ubuntu-latest
    env:
      NODE_URL: ${{ secrets.AVALANCHE_NODE_URL }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup env
        uses: ./.github/actions/setup-env

      - name: Running Aave strategy for VAUSDCe pool
        run: npm test test/avalanche/aave/vausdce.js

  vawbtce-test:
    needs: [setup-job]
    runs-on: ubuntu-latest
    env:
      NODE_URL: ${{ secrets.AVALANCHE_NODE_URL }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup env
        uses: ./.github/actions/setup-env

      - name: Running Aave strategy for VAWBTCe pool
        run: npm test test/avalanche/aave/vawbtce.js

  vawethe-test:
    needs: [setup-job]
    runs-on: ubuntu-latest
    env:
      NODE_URL: ${{ secrets.AVALANCHE_NODE_URL }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup env
        uses: ./.github/actions/setup-env

      - name: Running Aave strategy for VAWETHe pool
        run: npm test test/avalanche/aave/vawethe.js
