name: CI vaavax Unit Test
on:
  schedule:
    - cron: "0 2 * * *" # run at 2 AM UTC
  pull_request:
    paths:
      - ".github/workflows/ci-vaavax-unit-test.yml"

jobs:
  ci-vaavax-unit-test:
    runs-on: ubuntu-latest
    env:
      NODE_URL: ${{ secrets.NODE_URL }}
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          submodules: true
      - run: cat "${GITHUB_WORKSPACE}/.github/env.properties" >> $GITHUB_ENV

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version-file: ".nvmrc"

      - name: Run npm install
        run: npm install

      - name: Running vaAVAX unit tests
        run: |
          npm test test/avalanche/vaavax/*.js -- --parallel
