name: CI vamusd Unit Test 
on:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC
  pull_request:
    paths:
      - ".github/workflows/ci-vamusd-unit-test.yml"
      
jobs:
  ci-vamusd-unit-test:
    runs-on: ubuntu-latest
    env:
      NODE_URL: ${{ secrets.NODE_URL }}
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          submodules: true
      - run: cat "${GITHUB_WORKSPACE}/.github/env.properties" >> $GITHUB_ENV

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'

      - name: Run npm install
        run: npm install

      - name: Running vamusd unit tests
        run: |
          npm test test/vamusd/*.js -- --parallel
