name: Mainnet Earn Aave Strategy
on:
  pull_request:
    paths:
      - ".github/workflows/mainnet-earn-aave.yml"
      - ".github/actions/setup-env/action.yml"
      - "contracts/pool/**/*.sol"
      - "contracts/pool/*.sol"
      - "contracts/strategies/Strategy.sol"
      - "contracts/strategies/Earn.sol"
      - "contracts/strategies/aave/AaveStrategy.sol"
      - "contracts/strategies/aave/AaveCore.sol"
      - "contracts/strategies/aave/earn/**"
      - "test/mainnet/earn/aave/**"

# Limit concurrency to one workflow per branch and one per pull_request
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  setup-job:
    runs-on: ubuntu-latest
    env:
      NODE_URL: ${{ secrets.NODE_URL }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup env
        uses: ./.github/actions/setup-env

  veeth-dai-test:
    needs: [setup-job]
    runs-on: ubuntu-latest
    env:
      NODE_URL: ${{ secrets.NODE_URL }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup env
        uses: ./.github/actions/setup-env

      - name: Running Earn Aave strategy for VEETH_DAI pool
        run: npm test test/mainnet/earn/aave/veeth-dai.js
