name: Mainnet Maker Strategy
on:
  pull_request:
    paths:
      - ".github/workflows/mainnet-maker.yml"
      - ".github/actions/setup-env/action.yml"
      - "test/utils/setupHelper.js"
      - "test/behavior/maker-strategy.js"
      - "contracts/pool/**/*.sol"
      - "contracts/pool/*.sol"
      - "contracts/strategies/Strategy.sol"
      - "contracts/strategies/maker/*.sol"
      - "contracts/strategies/aave/AaveCore.sol"
      - "test/mainnet/maker/**/*.js"

# Limit concurrency to one workflow per branch and one per pull_request
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  setup-job:
    runs-on: ubuntu-latest
    env:
      NODE_URL: ${{ secrets.NODE_URL }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup env
        uses: ./.github/actions/setup-env

  vaeth-aave-test:
    needs: [setup-job]
    runs-on: ubuntu-latest
    env:
      NODE_URL: ${{ secrets.NODE_URL }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup env
        uses: ./.github/actions/setup-env

      - name: Running Maker Aave strategy for VAETH pool
        run: npm test test/mainnet/maker/aave/vaeth.js

  vaeth-compound-test:
    needs: [setup-job]
    runs-on: ubuntu-latest
    env:
      NODE_URL: ${{ secrets.NODE_URL }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup env
        uses: ./.github/actions/setup-env

      - name: Running Maker Compound strategy for VAETH pool
        run: npm test test/mainnet/maker/compound/vaeth.js

  vauni-compound-test:
    needs: [setup-job]
    runs-on: ubuntu-latest
    env:
      NODE_URL: ${{ secrets.NODE_URL }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup env
        uses: ./.github/actions/setup-env

      - name: Running Maker Compound strategy for VAUNI pool
        run: npm test test/mainnet/maker/compound/vauni.js

  vaeth-vesper-test:
    needs: [setup-job]
    runs-on: ubuntu-latest
    env:
      NODE_URL: ${{ secrets.NODE_URL }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup env
        uses: ./.github/actions/setup-env

      - name: Running Maker Vesper strategy for VAETH pool
        run: npm test test/mainnet/maker/vesper/vaeth.js

  vawbtc-vesper-test:
    needs: [setup-job]
    runs-on: ubuntu-latest
    env:
      NODE_URL: ${{ secrets.NODE_URL }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup env
        uses: ./.github/actions/setup-env

      - name: Running Maker Vesper strategy for VAWBTC pool
        run: npm test test/mainnet/maker/vesper/vawbtc.js
