name: VPool Admin, Proxy and Rewards test
on:
  pull_request:
    paths:
      - ".github/workflows/pool-admin.yml"
      - "test/*.js"
      - "contracts/pool/*.sol"

jobs:
  vesper-pool-test:
    runs-on: ubuntu-latest
    env:
      NODE_URL: ${{ secrets.NODE_URL }}
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          submodules: true
      - run: cat "${GITHUB_WORKSPACE}/.github/env.properties" >> $GITHUB_ENV

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version-file: ".nvmrc"

      - name: Run npm install
        run: npm install

      - name: Running tests for Vesper Pool Admin
        run: npm test "test/vesper-pool-admin.js"

      - name: Running tests for Vesper Pool Proxy upgrade
        run: npm test "test/vesper-pool-proxy.js"

      - name: Running tests for Vesper PoolRewards
        run: npm test "test/pool-rewards.js"

      - name: Running tests for Vesper Pool Accountant Proxy upgrade
        run: npm test "test/pool-accountant-proxy.js"

      - name: Running tests for Vesper Pool Accountant
        run: npm test "test/pool-accountant.js"
