name: vaAVAX with Vesper TraderJoe XY.
on:
  pull_request:
    paths:
      - "test/avalanche/vaavax/vesper-trader-joe-xy.js"
      - "contracts/strategies/Strategy.sol"
      - "contracts/strategies/compound/CompoundXYCore.sol"
      - "contracts/strategies/compound/TraderJoeXYStrategy.sol"
      - "contracts/strategies/compound/VesperTraderJoeXYStrategy.sol"

jobs:
  vaavax-vesper-trader-joe-xy-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          submodules: true
      - run: cat "${GITHUB_WORKSPACE}/.github/avalanche.env.properties" >> $GITHUB_ENV

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version-file: ".nvmrc"

      - name: Run npm install
        run: npm install

      - name: Running tests for vaAVAX Vesper TraderJoe XY
        run: BLOCK_NUMBER=13942928 npm test test/avalanche/vaavax/vesper-trader-joe-xy.js
