name: vaAVAX with Alpha Lend Avalanche Strategy
on:
  pull_request:
    paths:
      - "test/vaavax/alpha-lend-avalanche.js"
      - "contracts/strategies/Strategy.sol"
      - "contracts/strategies/alpha/AlphaLendStrategy.sol"
      - "contracts/strategies/alpha/AlphaLendAvalancheStrategy.sol"
      - "contracts/strategies/alpha/AlphaLendAvalancheStrategyAVAX.sol"
      - "contracts/strategies/alpha/AlphaLendStrategyETH.sol"
      
jobs:
  vaavax-alpha-lend-avalanche-strategy-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          submodules: true
      - run: cat "${GITHUB_WORKSPACE}/.github/avalanche.env.properties" >> $GITHUB_ENV

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'

      - name: Run npm install with node v${{ matrix.node }}
        run: npm install

      - name: Running tests for vaAVAX Alpha Lend Avalanche
        run: npm test "test/vaavax/alpha-lend-avalanche.js"
