name: vaDAI with Aave Leverage
on:
  pull_request:
    paths:
      - "test/vadai/aave-leverage.js"
      - "contracts/strategies/Strategy.sol"
      - "contracts/strategies/aave/AaveLeverageStrategy.sol"
      - "contracts/strategies/aave/AaveCore.sol"

jobs:
  vadai-aave-leverage-test:
    runs-on: ubuntu-latest
    env:
      NODE_URL: ${{ secrets.NODE_URL }}
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          submodules: true
      - run: cat "${GITHUB_WORKSPACE}/.github/env.properties" >> $GITHUB_ENV

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version-file: ".nvmrc"

      - name: Run npm install
        run: npm install

      - name: Running vaDAI with Aave Leverage
        run: BLOCK_NUMBER=14572476 npm test "test/vadai/aave-leverage.js"
