name: vaWBTC with Alpha Lend Avalanche Strategy
on:
  pull_request:
    paths:
      - "test/avalanche/vawbtc/alpha-lend-avalanche.js"
      - "contracts/strategies/Strategy.sol"
      - "contracts/strategies/alpha/AlphaLendStrategy.sol"
      - "contracts/strategies/alpha/AlphaLendAvalancheStrategy.sol"

jobs:
  vawbtc-alpha-lend-avalanche-strategy-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          submodules: true
      - run: cat "${GITHUB_WORKSPACE}/.github/avalanche.env.properties" >> $GITHUB_ENV

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version-file: ".nvmrc"

      - name: Run npm install
        run: npm install

      - name: Running tests for vaWBTC Alpha Lend Avalanche
        run: npm test "test/avalanche/vawbtc/alpha-lend-avalanche.js"
