name: vaWBTC with Vesper Benqi XY
on:
  pull_request:
    paths:
      - "test/avalanche/vawbtc/vesper-benqi-xy.js"
      - "contracts/strategies/Strategy.sol"
      - "contracts/strategies/compound/CompoundXYCore.sol"
      - "contracts/strategies/compound/CompoundXYStrategy.sol"
      - "contracts/strategies/compound/BenqiXYStrategy.sol"
      - "contracts/strategies/compound/VesperBenqiXYStrategy.sol"

jobs:
  vawbtc-benqi-strategy-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: cat "${GITHUB_WORKSPACE}/.github/avalanche.env.properties" >> $GITHUB_ENV

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version-file: ".nvmrc"

      - name: Run npm install
        run: npm install

      - name: Running tests for vaWBTC Vesper Benqi XY
        run: npm test "test/avalanche/vawbtc/vesper-benqi-xy.js"
