name: vaWETH with Benqi Compound
on:
  pull_request:
    paths:
      - "test/avalanche/vaweth/benqi.js"
      - "contracts/strategies/Strategy.sol"
      - "contracts/strategies/compound/CompoundStrategy.sol"
      - "contracts/strategies/compound/CompoundMultiRewardAvalancheStrategy.sol"

jobs:
  vaweth-benqi-strategy-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          submodules: true
      - run: cat "${GITHUB_WORKSPACE}/.github/avalanche.env.properties" >> $GITHUB_ENV

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version-file: ".nvmrc"

      - name: Run npm install
        run: npm install

      - name: Running tests for vaWETH Benqi Compound
        run: npm test "test/avalanche/vaweth/benqi.js"
