name: veETH-DAI Earn with Compound Maker
on:
  pull_request:
    paths:
      - "test/utils/setupHelper.js"
      - "test/veth/earn-compound-maker.js"
      - "contracts/strategies/Strategy.sol"
      - "contracts/strategies/maker/CompoundMakerStrategy.sol"
      - "contracts/strategies/maker/MakerStrategy.sol"
      - "contracts/strategies/maker/earn/EarnCompoundMakerStrategy.sol"
      - ".github/workflows/veth-earn-compound-maker.yml"

jobs:
  veth-earn-compound-maker:
    runs-on: ubuntu-latest
    env:
      NODE_URL: ${{ secrets.NODE_URL }}
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          submodules: true
      - run: cat "${GITHUB_WORKSPACE}/.github/env.properties" >> $GITHUB_ENV

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'

      - name: Run npm install with node v${{ matrix.node }}
        run: npm install

      - name: Running veETH-DAI with Compound Maker
        run: npm test "test/veth/earn-compound-maker.js"
